version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQA_TEST_ALL_8825Project
  gitServerName: rimaSCName
  gitUrl: https://github.com/rimabarman
  gitUsername: rimabarman
  gitBranch: main
- name: TPP_services_in_FCS
  gitServerName: kvv
  gitUrl: https://github.com/Karthik-V-IBM-10
  gitUsername: Karthik-V-IBM-10
  gitBranch: main
- name: SIQA_OriginTest_OnPremAssets
  gitServerName: rimaSCName
  gitUrl: https://github.com/vijetadixit
  gitUsername: rimabarman
  gitBranch: Test2
services:
- serviceName: project.siqa_test_all_8825.integrations:AlertsCRTandERT
  packages:
  - name: SIQA_TEST_ALL_8825Project
    version: "1.0"
- serviceName: pub.alert:emit
  packages:
  - name: WmPublic
    version: 11.1.0.0.2076
- serviceName: project.siqa_test_all_8825.integrations:deepclonetest
  packages:
  - name: SIQA_TEST_ALL_8825Project
    version: "1.0"
- serviceName: pub.string:stringToBytes
  packages:
  - name: WmPublic
    version: 11.1.0.0.2076
- serviceName: pub.utils:deepClone
  packages:
  - name: WmPublic
    version: 11.1.0.0.2076
- serviceName: pub.string:bytesToString
  packages:
  - name: WmPublic
    version: 11.1.0.0.2076
